use_frameworks!

##忽略.cocoapods中多个specs源引起的警告问题
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

platform :ios, '13.0'

target 'ZHHSlidePopupView_Example' do
  pod 'ZHHSlidePopupView', :path => '../'

  target 'ZHHSlidePopupView_Tests' do
    inherit! :search_paths

    
  end
end
